import investpy
import time
from datetime import datetime, timedelta
from rsi import get_rsi
from macd import get_macd
import pandas as pd
from tabulate import tabulate
from sendgrid_handler import send_email

TURNOVER_LIMIT = 500000.0


def get_high_priority_shares(all_shares):
    priority_shares = {}

    for share in all_shares:
        try:
            search_result = investpy.search_quotes(text=all_shares[share], products=['stocks'],
                                                   countries=['sri lanka'], n_results=1)
            information = search_result.retrieve_information()

            estimated_turn_over = information['open'] * information['volume']

            if estimated_turn_over > TURNOVER_LIMIT:
                # print(share, estimated_turn_over)
                priority_shares[share] = all_shares[share]
        except Exception:
            print('Could not find', share)
            pass

    return priority_shares


def get_data(share_name, days=30):
    today = datetime.today().strftime("%d/%m/%Y")
    start_date = datetime.today() - timedelta(days=days)
    start_date = start_date.strftime("%d/%m/%Y")

    df = investpy.get_stock_historical_data(stock=share_name,
                                            country='sri lanka',
                                            from_date=start_date,
                                            to_date=today)

    return df


if __name__ == '__main__':
    all_shares = {'CITY HOUSING & REAL ESTATE CO. PLC': 'CHOU', 'AITKEN SPENCE PLANTATION MANAGEMENTS PLC': 'ASPM', 'PARAGON CEYLON PLC': 'PARA', 'OFFICE EQUIPMENT PLC': 'OFEQ', 'CEYLON & FOREIGN TRADES PLC': 'CFT', 'HUEJAY INTERNATIONAL INVESTMENTS PLC': 'HUEJ', 'TESS AGRO PLC': 'TESS', 'CEYLINCO INSURANCE PLC': 'CINS', 'STANDARD CAPITAL PLC': 'SING', 'MTD WALKERS PLC': 'KAPI', 'LANKA CEMENT PLC': 'LCEM', 'CEYLON PRINTERS PLC': 'CPRT', 'AGSTAR PLC': 'AGST', 'ADAM CAPITAL PLC': 'PCHH', 'SWARNAMAHAL FINANCIAL SERVICES PLC': 'SFS', 'AMW CAPITAL LEASING AND FINANCE PLC': 'AMCL', 'MERCANTILE INVESTMENTS AND FINANCE PLC': 'MERC', 'SENKADAGALA FINANCE PLC': 'SFCL', 'LUCKY LANKA MILK PROCESSING COMPANY PLC': 'LLMP', 'ADAM INVESTMENTS PLC': 'AINV', 'SWADESHI INDUSTRIAL WORKS PLC': 'SWAD', 'CONVENIENCE FOODS (LANKA )PLC': 'SOY', 'ARPICO INSURANCE PLC': 'AINS', 'TRANS ASIA HOTELS PLC': 'TRAN', 'NAMUNUKULA PLANTATIONS PLC': 'NAMU', 'SERENDIB HOTELS PLC': 'SHOT', 'BOGAWANTALAWA TEA ESTATES PLC': 'BOPL', 'C T LAND DEVELOPMENT PLC': 'CTLD', 'HAPUGASTENNE PLANTATIONS PLC': 'HAPU', 'KAHAWATTE PLANTATIONS PLC': 'KAHA', 'MAHAWELI REACH HOTELS PLC': 'MRH', 'MERCHANT BANK OF SRI LANKA & FINANCE PLC': 'MBSL', 'KELSEY DEVELOPMENTS PLC': 'KDL', 'CEYLON BEVERAGE HOLDINGS PLC': 'BREW', 'HIKKADUWA BEACH RESORT PLC': 'CITH', 'LANKA ASHOK LEYLAND PLC': 'ASHO', 'RENUKA CITY HOTEL PLC': 'RENU', 'LANKA CERAMIC PLC': 'CERA', 'LANKEM CEYLON PLC': 'LCEY', 'COLOMBO DOCKYARD PLC': 'DOCK', 'BROWNS BEACH HOTELS PLC': 'BBH', 'THE LIGHTHOUSE HOTEL PLC': 'LHL', 'GUARDIAN CAPITAL PARTNERS PLC': 'WAPO', 'BANSEI ROYAL RESORTS HIKKADUWA PLC': 'BRR', 'LION BREWERY CEYLON PLC': 'LION', 'ODEL PLC': 'ODEL', 'UNITED MOTORS LANKA PLC': 'UML', 'CEYLON HOSPITALS PLC (DURDANS)': 'CHL', 'SATHOSA MOTORS PLC': 'SMOT', 'EQUITY TWO PLC': 'ETWO', 'SERENDIB LAND PLC': 'SLND', 'MILLENNIUM HOUSING DEVELOPERS PLC': 'MHDL', 'CITRUS LEISURE PLC': 'REEF', 'CEYLON HOTELS CORPORATION PLC': 'CHOT', 'COMMERCIAL DEVELOPMENT COMPANY PLC': 'COMD', 'THE FORTRESS RESORTS PLC': 'RHTL', 'SINGER FINANCE (LANKA) PLC': 'SFIN', 'PRINTCARE PLC': 'CARE', 'DIESEL & MOTOR ENGINEERING PLC': 'DIMO', 'RENUKA AGRI FOODS PLC': 'RAL', 'SOFTLOGIC CAPITAL PLC': 'SCAP', 'SERENDIB ENGINEERING GROUP PLC': 'IDL', 'ACME PRINTING & PACKAGING PLC': 'ACME', 'E-CHANNELLING PLC': 'ECL', 'RENUKA HOLDINGS PLC': 'RHL', 'ALLIANCE FINANCE COMPANY PLC': 'ALLI', 'BUKIT DARAH PLC': 'BUKI', 'THE LANKA HOSPITALS CORPORATION PLC': 'LHCL', 'ASIA CAPITAL PLC': 'ACAP', 'COLOMBO INVESTMENT TRUST PLC': 'CIT', 'LANKA VENTURES PLC': 'LVEN', 'AGALAWATTE PLANTATIONS PLC': 'AGAL', 'ROYAL PALMS BEACH HOTELS PLC': 'RPBH', 'CARGILLS (CEYLON) PLC': 'CARG', 'HUNAS FALLS HOTELS PLC': 'HUNA', 'LAKE HOUSE PRINTERS AND PUBLISHERS PLC': 'LPRT', 'BLUE DIAMONDS JEWELLERY WORLDWIDE PLC': 'BLUE', 'PEOPLE`S MERCHANT FINANCE PLC': 'PMB', 'EASTERN MERCHANTS PLC': 'EMER', 'HOTEL SIGIRIYA PLC': 'HSIG', 'AMBEON CAPITAL PLC': 'TAP', 'SRI LANKA TELECOM PLC': 'SLTL', 'SANASA DEVELOPMENT BANK PLC': 'SDB', 'CEYLON GUARDIAN INVESTMENT TRUST PLC': 'GUAR', 'JOHN KEELLS HOTELS PLC': 'KHL', 'UNION ASSURANCE PLC': 'UAL', 'DANKOTUWA PORCELAIN PLC': 'DPL', 'RENUKA FOODS PLC': 'COCO', 'LOTUS HYDRO POWER PLC': 'HPFL', 'SHALIMAR (MALAY) PLC': 'SHAL', 'VIDULLANKA PLC': 'VLL', 'MALWATTE VALLEY PLANTATIONS PLC': 'MAL', 'AITKEN SPENCE HOTEL HOLDINGS PLC': 'AHUN', 'COLOMBO CITY HOLDINGS PLC': 'PHAR', 'TEA SMALLHOLDER FACTORIES PLC': 'TSML', 'ASIRI SURGICAL HOSPITAL PLC': 'AMSL', 'YORK ARCADE HOLDINGS PLC': 'YORK', 'RICHARD PIERIS AND COMPANY PLC': 'RICH', 'AMANA BANK PLC': 'ABL', 'KOTMALE HOLDINGS PLC': 'LAMB', 'GALADARI HOTELS (LANKA) PLC': 'GHLL', 'ACL PLASTICS PLC': 'APLA', 'SAMSON INTERNATIONAL PLC': 'SIL', 'MARAWILA RESORTS PLC': 'MARA', 'MACKWOODS ENERGY PLC': 'MEL', 'RICHARD PIERIS EXPORTS PLC': 'REXP', 'LOLC DEVELOPMENT FINANCE PLC': 'NIFL', 'KEGALLE PLANTATIONS PLC': 'KGAL', 'SINGHE HOSPITALS PLC': 'SINH', 'LANKEM DEVELOPMENTS PLC': 'LDEV', 'PRIME FINANCE PLC': 'GSF', 'RENUKA CAPITAL PLC': 'KZOO', 'MASKELIYA PLANTATIONS PLC': 'MASK', 'MADULSIMA PLANTATIONS PLC': 'MADU', 'TAL LANKA HOTELS PLC': 'TAJ', 'PALM GARDEN HOTELS PLC': 'PALM', 'THE COLOMBO FORT LAND & BUILDING PLC': 'CFLB', 'PANASIAN POWER PLC': 'PAP', 'ORIENT FINANCE PLC': 'BFN', 'JOHN KEELLS PLC': 'JKL', 'ELPITIYA PLANTATIONS PLC': 'ELPL', 'SINGER (SRI LANKA) PLC': 'SINS', 'BERUWALA RESORTS PLC': 'BERU', 'B P P L HOLDINGS PLC': 'BPPL', 'FIRST CAPITAL HOLDINGS PLC': 'CFVF', 'ABANS FINANCE PLC': 'AFSL', 'ANILANA HOTELS AND PROPERTIES PLC': 'ALHP', 'VALLIBEL POWER ERATHNA PLC': 'VPEL', 'CENTRAL FINANCE COMPANY PLC': 'CFIN', 'LAUGFS GAS PLC': 'LGL', 'LAXAPANA BATTERIES PLC': 'LITE', 'KEELLS FOOD PRODUCTS PLC': 'KFP', 'ASIA SIYAKA COMMODITIES PLC': 'ASIY', 'REGNIS(LANKA) PLC': 'REG', 'CEYLON TOBACCO COMPANY PLC': 'CTC', 'UNISYST ENGINEERING PLC': 'ALUF', 'CITIZENS DEVELOPMENT BUSINESS FINANCE PLC': 'CDB', 'SIERRA CABLES PLC': 'SIRA', 'HOUSING DEVELOPMENT FINANCE CORPORATION BANK OF SRI LANKA': 'HDFC', 'COMMERCIAL CREDIT AND FINANCE PLC': 'COCR', 'LEE HEDGES PLC': 'SHAW', 'NATIONS TRUST BANK PLC': 'NTB', 'RAMBODA FALLS PLC': 'RFL', 'CENTRAL INDUSTRIES PLC': 'CIND', 'JANASHAKTHI INSURANCE PLC': 'JINS', 'LANKA IOC PLC': 'LIOC', 'RESUS ENERGY PLC': 'HPWR', 'NAWALOKA HOSPITALS PLC': 'NHL', 'WASKADUWA BEACH RESORT PLC': 'CITW', 'SOFTLOGIC FINANCE PLC': 'CRL', 'EAST WEST PROPERTIES PLC': 'EAST', 'SELINSING PLC': 'SELI', 'LANKA REALTY INVESTMENTS PLC': 'ASCO', "PEOPLE'S INSURANCE PLC": 'PINS', 'ABANS ELECTRICALS PLC': 'ABAN', 'EDEN HOTEL LANKA PLC': 'EDEN', 'TALAWAKELLE TEA ESTATES PLC': 'TPL', 'PEGASUS HOTELS OF CEYLON PLC': 'PEG', 'DIALOG FINANCE PLC': 'CALF', 'NESTLE LANKA PLC': 'NEST', 'COMMERCIAL BANK OF CEYLON PLC': 'COMB', 'CEYLON INVESTMENT PLC': 'CINV', 'SUNSHINE HOLDINGS PLC': 'SUN', 'KELANI VALLEY PLANTATIONS PLC': 'KVAL', 'CEYLON TEA BROKERS PLC': 'CTBL', 'ASSOCIATED MOTOR FINANCE COMPANY PLC': 'AMF', 'SEYLAN BANK PLC': 'SEYB', 'WATAWALA PLANTATIONS PLC': 'WATA', 'COMMERCIAL LEASING & FINANCE PLC': 'CLC', 'KELANI TYRES PLC': 'TYRE', 'SWISSTEK (CEYLON) PLC': 'PARQ', 'C M HOLDINGS PLC': 'COLO', 'MULLER AND PHIPPS (CEYLON) PLC': 'MULL', 'SINGER INDUSTRIES (CEYLON) PLC': 'SINI', 'THE KANDY HOTELS COMPANY (1938) PLC': 'KHC', 'CHEMANEX PLC': 'CHMX', 'HAYLEYS LEISURE PLC': 'CONN', 'CIC HOLDINGS PLC': 'CIC', 'AITKEN SPENCE PLC': 'SPEN', 'UNION BANK OF COLOMBO PLC': 'UBC', 'TANGERINE BEACH HOTELS PLC': 'TANG', 'NATION LANKA FINANCE PLC': 'CSF', 'THREE ACRE FARMS PLC': 'TAFL', 'ASIRI HOSPITAL HOLDINGS PLC': 'ASIR', 'COLOMBO FORT INVESTMENTS PLC': 'CFI', 'ASIA ASSET FINANCE PLC': 'AAF', 'SIGIRIYA VILLAGE HOTELS PLC': 'SIGV', 'HAYCARB PLC': 'HAYC', 'PIRAMAL GLASS CEYLON PLC': 'GLAS', 'LOLC HOLDINGS PLC': 'LOLC', 'BROWNS INVESTMENTS PLC': 'BIL', 'HAYLEYS FIBRE PLC': 'HEXP', 'DIALOG AXIATA PLC': 'DIAL', 'KELANI CABLES PLC': 'KCAB', 'LANKA ALUMINIUM INDUSTRIES PLC': 'LALU', 'ALUMEX PLC': 'ALUM', 'DIPPED PRODUCTS PLC': 'DIPD', 'ACL CABLES PLC': 'ACL', 'PAN ASIA BANKING CORPORATION PLC': 'PABC', 'EXPOLANKA HOLDINGS PLC': 'EXPO', 'ROYAL CERAMICS LANKA PLC': 'RCL', 'HAYLEYS FABRIC PLC': 'MGT', 'SAMPATH BANK PLC': 'SAMP', 'TOKYO CEMENT COMPANY (LANKA) PLC': 'TKYO', 'HAYLEYS PLC': 'HAYL', 'RAIGAM WAYAMBA SALTERNS PLC': 'RWSL', 'JOHN KEELLS HOLDINGS PLC': 'JKH', 'LOLC FINANCE PLC': 'LOFC', 'VALLIBEL ONE PLC': 'VONE', 'AMBEON HOLDINGS PLC': 'GREG', "PEOPLE'S LEASING & FINANCE PLC": 'PLC', 'BALANGODA PLANTATIONS PLC': 'BALA', 'COLOMBO LAND & DEVELOPMENT COMPANY PLC': 'CLND', 'LANKA MILK FOODS (CWE) PLC': 'LMF', 'ACCESS ENGINEERING PLC': 'AEL', 'HATTON NATIONAL BANK PLC': 'HNB', 'HNB ASSURANCE PLC': 'HASU', 'BROWN & COMPANY PLC': 'BRWN', 'CEYLON GRAIN ELEVATORS PLC': 'GRAN', 'LANKA TILES PLC': 'TILE', 'MULTI FINANCE PLC': 'MFL', 'DISTILLERIES COMPANY OF SRI LANKA PLC': 'DIST', 'R I L PROPERTY PLC': 'RIL', 'TEEJAY LANKA PLC': 'TJL', 'CEYLON COLD STORES PLC': 'CCS', 'DFCC BANK PLC': 'DFCC', 'HEMAS HOLDINGS PLC': 'HHL', 'KOTAGALA PLANTATIONS PLC': 'KOTA', 'SOFTLOGIC HOLDINGS PLC': 'SHL', 'HARISCHANDRA MILLS PLC': 'HARI', 'E B CREASY & COMPANY PLC': 'EBCR', 'LANKA WALLTILES PLC': 'LWL', 'MELSTACORP PLC': 'MELS', 'CHEVRON LUBRICANTS LANKA PLC': 'LLUB', 'INDUSTRIAL ASPHALTS (CEYLON) PLC': 'ASPH', 'OVERSEAS REALTY (CEYLON) PLC': 'OSEA', 'THE KINGSBURY PLC': 'SERV', 'SOFTLOGIC LIFE INSURANCE PLC': 'AAIC', 'VALLIBEL FINANCE PLC': 'VFIN', 'BOGALA GRAPHITE LANKA PLC': 'BOGA', 'BAIRAHA FARMS PLC': 'BFL', 'SMB LEASING PLC': 'SEMB', 'C. W. MACKIE PLC': 'CWM', 'HVA FOODS PLC': 'HVA', 'AMANA TAKAFUL PLC': 'ATL', 'CARSON CUMBERBATCH PLC': 'CARS', 'UDAPUSSELLAWA PLANTATIONS PLC': 'UDPL', 'CARGO BOAT DEVELOPMENT COMPANY PLC': 'CABO', 'NATIONAL DEVELOPMENT BANK PLC': 'NDB', 'L B FINANCE PLC': 'LFIN', 'THE NUWARA ELIYA HOTELS COMPANY PLC': 'NEH', 'THE AUTODROME PLC': 'AUTO', 'AMANA TAKAFUL LIFE PLC': 'ATLL', 'ASIAN HOTELS & PROPERTIES PLC': 'AHPL', 'GESTETNER OF CEYLON PLC': 'GEST', 'HUNTERS & COMPANY PLC': 'HUNT', 'BIMPUTH FINANCE PLC': 'BLI', 'DILMAH CEYLON TEA COMPANY PLC': 'CTEA', 'ON ALLY HOLDINGS PLC': 'ONAL', 'DOLPHIN HOTELS PLC': 'STAF', 'MERCANTILE SHIPPING COMPANY PLC': 'MSL', 'INDO MALAY PLC': 'INDO', 'GOOD HOPE PLC': 'GOOD', 'SEYLAN DEVELOPMENTS PLC': 'CSD', 'HORANA PLANTATIONS PLC': 'HOPL', 'UNION CHEMICALS LANKA PLC': 'UCAR', 'SINHAPUTHRA FINANCE PLC': 'SFL', 'PROPERTY DEVELOPMENT PLC': 'PDL', 'C T HOLDINGS PLC': 'CTHR', 'RADIANT GEMS INTERNATIONAL PLC': 'RGEM'}
    # print(len(all_shares))

    while True:
        days_from_beginning = int(time.time()/(24 * 60 * 60))
        start_of_next_day = (days_from_beginning + 1) * 24 * 60 * 60
        time.sleep(start_of_next_day - time.time() - 5.5*60*60)

        shares = get_high_priority_shares(all_shares=all_shares)

        data = {'Stock': [],
                'Symbol': [],
                'RSI': [],
                'MACD': [],
                'Signal': [],
                'Diff': [],
                ' ': []}
        for share in shares:
            try:
                df = get_data(shares[share])
                RSI = get_rsi(df.Open.to_numpy(), df.Close.to_numpy())
                macd, signal, diff = get_macd(shares[share])

                data['Stock'].append(share)
                data['Symbol'].append(shares[share])
                data['RSI'].append(round(RSI))
                data['MACD'].append(macd)
                data['Signal'].append(signal)
                data['Diff'].append(diff)
                data[' '].append('buy' if macd > signal else 'sell')
            except RuntimeError:
                print('Error', share)
                pass

        df = pd.DataFrame(data=data)
        df = df.sort_values(by=['RSI'])
        send_email(df.to_html(), title="Stock Market Update")
        # print(df.to_markdown())
        time.sleep(60)
